# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e675069e190e7f3a420ccc21b55bb709256bc4c03009f46bc71d41cdef5da254e1e5bc4a9553a2779bd40f0276dcf40b6e40aba4b6c2b0f3074fd533d39c39f9

test:
  secret_key_base: 28e01d51c2a66158f3cdc771846eefbc0bb734026e8f934d78aa0c5efd91aa212fa5fcb14e0e4a458628a1322617fb0a81840ff517774e6d16993c226d39f818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
